export const EXPENSE_CATEGORIES = [
  // OFFICE EXPENSES
  "office rent",
  "warehouse rent",
  "electricity&water",
  "property management",
  "office supplies",
  "service maintenance",
  "tools & spare part",
  "drinking water",
  "legal&professional fee",
  "personnel recruitment",
  "document expense",
  "telephone&fax",
  "internet",
  "supplies",
  "Tax Reklame",
  // FIXED ASSETS&PREPAID EXPENSES
  "vehicle",
  "computer",
  "printer",
  "projector",
  "office furniture",
  "office appliances",
  "exhibitions (FA)",
  "space branding rent (FA)",
  "operating rental (FA)",
  "office rent (Prepaid)",
  "warehouse rent (Prepaid)",
  "property management (Prepaid)",
  "vehicle rent",
  "asset insurance",
  "mobil insurance",
  // LOGISTICS & CAR EXPENSES
  "car rental",
  "delivery",
  "express",
  "gasoline",
  "parking",
  "toll",
  "repairing",
  // EMPLOYEE EXPENSES
  "social insurance",
  "medical insurance",
  "accident insurance",
  "welfare",
  "training expenses",
  "Service fee",
  "allowance",
  "Transportation",
  "Hotel",
  "taxi",
  "Bonus",
  // MARKETING EXPENSES
  "exhibitions",
  "space branding rent",
  "operating rental",
  "advertising/promotion",
  "Marketing Fee",
  "claim price protection",
  "Adv. Production/installation",
  "Adv. Material",
  "public relation activity",
  "BNS entertain-meals",
  "BNS entertain-entertainment",
  "BNS entertain-hotel expense",
  "BNS entertain-Transportation",
  "BNS entertain-gift",
  "meeting-meals",
  "meeting-accommodation",
  "meeting-rental",
  "meeting-gift"
]
